
server:
  port: 8194
  context-path: /

# \u670D\u52A1\u8282\u70B9,\u8981\u6C42\u5206\u5E03\u5F0F\u4E0B\u6BCF\u4E2A\u8282\u70B9\u4E0D\u540C
node: 01

spring:
  dubbo:
    application:
      name: xxpay-assistant
    registry:
      address: @zookeeper.url@
    scan: org.xxpay.asst
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
    active: dev

# JWT
jwt:
  cookie: XxPay_Asst_Token
  secret: XxpPayGood
  expiration: 604800 # 7\u5929

logging:
  file: ./log/xxpay-assistant.log

config:
  appId: wx077cb62e341f8a5c
  appSecret: e663ea068f3e4f952f143de1432a35c2
  token:
  aesKey:
  mchApiUrl: @mch.site.url@/api
  downMchBillUrl: @reconciliation.site.url@/mch_bill_down
  redirectWxCodeUrl: @mch.site.url@/get-weixin-code.html
  payUrl: @pay.site.url@/api
  notifyUrl: @mch.site.url@/api/payment/notify
